// Comprehensive Fitness and Health Knowledge Base with Sentence Understanding and Meal Planning
export const fitnessHealthData = {
  greetings: {
    patterns: [
      /hello/i,
      /hi/i,
      /hey/i,
      /good morning/i,
      /good afternoon/i,
      /good evening/i,
      /what's up/i,
      /how are you/i,
      /yo/i,
      /what's good/i,
      /how's it going/i,
      /greetings/i,
    ],
    responses: [
      "Hello! Ready to talk about fitness and health? 💪",
      "Hi there! How can I help with your fitness journey today?",
      "Hey! Let's discuss health and wellness! 🏃‍♂️",
      "Hello! I'm here to help with all your fitness and health questions!",
      "Hi! Excited to help you achieve your health goals today! 🌟",
      "Hey! What fitness questions can I answer for you today? 🏋️‍♂️",
    ],
  },

  // ULTRA-COMPREHENSIVE: Enhanced workout category with advanced sentence patterns
  workouts: {
    patterns: [
      /workout/i,
      /exercise/i,
      /training/i,
      /cardio/i,
      /strength/i,
      /weight lifting/i,
      /gym/i,
      /running/i,
      /push.?up/i,
      /squat/i,
      /deadlift/i,
      /bench press/i,
      /pull.?up/i,
      /crunch/i,
      /plank/i,
      /burpee/i,
      /lunges?/i,
      /shoulder press/i,
      /bicep curl/i,
      /tricep extension/i,
      /leg press/i,
      /lat pulldown/i,
      /row.?ing/i,
      /fitness routine/i,
      /training program/i,
      /exercise plan/i,
      /how to (workout|exercise|train)/i,
      /best exercise/i,
      /effective workout/i,
      /what.*exercise/i,
      /how.*train/i,
      /which.*workout/i,
      /recommend.*exercise/i,
      /suggest.*workout/i,
      /create.*routine/i,
      /build.*program/i,
      /start.*exercising/i,
      /begin.*working out/i,
      /new.*fitness/i,
      /home workout/i,
      /gym routine/i,
      /daily exercise/i,
      /workout plan/i,
      /training schedule/i,
      /fitness plan/i,
      /exercise routine/i,
      /should I do.*(exercise|workout)/i,
      /what.*good.*for.*(chest|back|legs|arms|shoulders)/i,
      /how.*get.*stronger/i,
      /ways to.*exercise/i,
      /types of.*workout/i,
      /different.*exercise/i,
      /exercise.*benefits/i,
      /workout.*tips/i,
      /improve.*fitness/i,
      /better.*workout/i,
      /effective.*training/i,
      /maximize.*workout/i,
      /optimize.*exercise/i,
    ],
    responses: [
      "For beginners, start with 3 days of strength training and 2 days of cardio per week.",
      "A balanced workout routine should include strength training, cardio, and flexibility exercises.",
      "Remember to warm up for 5-10 minutes before workouts and cool down afterward!",
      "Progressive overload is key - gradually increase weight or reps to keep making gains.",
      "Focus on compound movements like squats, deadlifts, and bench presses for maximum efficiency.",
      "Proper form is more important than heavy weights - always prioritize technique!",
      "Mix up your routine every 4-6 weeks to prevent plateaus and keep making progress.",
      "Don't forget to include mobility work and stretching in your routine for injury prevention.",
      "The best workout is the one you'll consistently do. Find activities you enjoy!",
      "Listen to your body - rest when needed but push yourself during workouts.",
      "Compound exercises work multiple muscle groups simultaneously for efficient training.",
      "Include both high-intensity and low-intensity workouts for balanced fitness development.",
      "Track your workouts to monitor progress and stay motivated long-term.",
    ],
  },

  // ENHANCED: Workout Split Comparison with advanced sentence patterns
  workoutComparison: {
    patterns: [
      /is (ppl|push.?pull.?legs?) good/i,
      /is (upper.?lower|upper lower) good/i,
      /is (bro.?split|bro split) good/i,
      /which (split|workout) (is best|should I do)/i,
      /compare (ppl|upper.?lower|bro.?split)/i,
      /(ppl|upper.?lower|bro.?split) vs\.? (ppl|upper.?lower|bro.?split)/i,
      /best (split|routine|workout)/i,
      /should I do (ppl|push.?pull.?legs?|upper.?lower|bro.?split)/i,
      /(ppl|upper.?lower|bro.?split).*good/i,
      /good.*(ppl|upper.?lower|bro.?split)/i,
      /is (ppl|push.?pull.?legs?) good for (beginners|intermediate|advanced)/i,
      /is (upper.?lower|upper lower) good for (beginners|intermediate|advanced)/i,
      /is (bro.?split|bro split) good for (beginners|intermediate|advanced)/i,
      /should (beginners|intermediate|advanced) do (ppl|push.?pull.?legs?|upper.?lower|bro.?split)/i,
      /(ppl|upper.?lower|bro.?split) for (beginners|intermediate|advanced)/i,
      /(beginners|intermediate|advanced).*(ppl|upper.?lower|bro.?split)/i,
      /which.*better.*(ppl|upper.?lower|bro.?split)/i,
      /difference between.*(ppl|upper.?lower|bro.?split)/i,
      /what.*difference.*(ppl|upper.?lower|bro.?split)/i,
      /how.*choose.*(split|routine)/i,
      /which one.*should.*choose/i,
      /recommend.*split/i,
      /suggest.*routine/i,
      /what.*best.*for.*(beginners|intermediate|advanced)/i,
      /help.*choose.*workout/i,
      /can't decide.*split/i,
      /confused.*which.*routine/i,
      /what.*difference.*(ppl|upper lower|bro split)/i,
      /which.*better/i,
      /compare.*workouts?/i,
      /workout.*comparison/i,
      /routine.*compare/i,
      /how.*pick.*workout/i,
      /choose.*training.*split/i,
      /select.*workout.*routine/i,
      /decide.*exercise.*program/i,
      /what.*recommend.*for.*me/i,
      /which.*suits.*me/i,
    ],
    responses: [
      "**PPL (Push/Pull/Legs) - Great for:**\n• Intermediate to advanced lifters\n• Training each muscle 2x per week\n• Balanced frequency and volume\n• Good for both strength and hypertrophy\n• Flexible scheduling (3-6 days/week)\n\n**Upper/Lower - Great for:**\n• Beginners to intermediate lifters\n• Training each muscle 2x per week\n• Balanced approach\n• Good for strength building\n• 4 days/week is optimal\n\n**Bro Split - Great for:**\n• Advanced bodybuilders\n• High volume per muscle group\n• Experienced lifters with good recovery\n• Focus on one muscle group per day\n• 5-6 days/week schedule\n\n**Recommendation:**\n• **Beginners:** Start with Upper/Lower or Full Body\n• **Intermediate:** PPL or Upper/Lower work well\n• **Advanced:** PPL or Bro Split depending on goals",

      "**Which split is right for you?**\n\n**PPL:** Best if you can train 3-6 days/week and want balanced frequency. Great for most people!\n\n**Upper/Lower:** Perfect if you prefer 4 days/week training. Excellent for strength and balanced development.\n\n**Bro Split:** Ideal if you're advanced, have great recovery, and want maximum volume per muscle group.\n\n**All three are effective** when properly programmed and consistent! The best split is the one you'll stick with long-term.",

      "**Workout Split Effectiveness:**\n\n✅ **PPL:** Very effective for most people - hits each muscle 2x/week with good volume\n\n✅ **Upper/Lower:** Highly effective - great frequency and balanced approach\n\n✅ **Bro Split:** Effective for advanced lifters - allows high volume per session\n\n**Key Factors:**\n• Your training experience\n• Recovery ability\n• Schedule availability\n• Personal preferences\n• Specific goals (strength vs. hypertrophy)\n\n**Bottom Line:** Consistency and progressive overload matter more than the specific split!",
    ],
  },

  // ENHANCED: PPL Workout Plans with multiple variations and alternative phrasing
  pplWorkouts: {
    patterns: [
      /ppl workout/i,
      /push pull legs? workout/i,
      /provide.*ppl/i,
      /give.*ppl/i,
      /show.*ppl/i,
      /create.*ppl/i,
      /make.*ppl/i,
      /design.*ppl/i,
      /ppl routine/i,
      /push pull legs? routine/i,
      /ppl program/i,
      /push pull legs? program/i,
      /ppl training/i,
      /push pull legs? training/i,
      /ppl split workout/i,
      /push pull legs? split workout/i,
      /i want ppl/i,
      /need ppl workout/i,
      /looking for ppl/i,
      /suggest ppl/i,
      /recommend ppl/i,
      /can you.*ppl/i,
      /want.*ppl/i,
      /get.*ppl/i,
      /need.*push pull/i,
      /want.*push pull/i,
      /show.*push pull/i,
      /give.*push pull/i,
      /create.*push pull/i,
      /make.*push pull/i,
      /design.*push pull/i,
      /ppl plan/i,
      /push pull legs? plan/i,
      /ppl schedule/i,
      /push pull legs? schedule/i,
      /ppl split/i,
      /push pull legs? split/i,
      /i need a ppl/i,
      /can i get ppl/i,
      /hook me up with ppl/i,
      /ppl workout plan/i,
      /push pull legs? workout plan/i,
      /another ppl/i,
      /different ppl/i,
      /new ppl/i,
      /next ppl/i,
      /more ppl/i,
    ],
    responses: [
      `**PPL Workout Variation 1 - Balanced Strength & Hypertrophy**\n\n**Push Day (Chest, Shoulders, Triceps):**\n• Barbell Bench Press: 4x8-12\n• Overhead Press: 3x8-12\n• Incline Dumbbell Press: 3x10-15\n• Lateral Raises: 3x12-15\n• Tricep Pushdowns: 3x12-15\n• Skull Crushers: 3x10-12\n\n**Pull Day (Back, Biceps):**\n• Pull-ups/Lat Pulldowns: 4x8-12\n• Barbell Rows: 4x8-12\n• Face Pulls: 3x15-20\n• Bicep Curls: 3x10-15\n• Hammer Curls: 3x10-15\n• Seated Cable Rows: 3x10-12\n\n**Legs Day (Quads, Hamstrings, Glutes, Calves):**\n• Squats: 4x6-10\n• Deadlifts: 3x5-8\n• Leg Press: 3x10-15\n• Leg Curls: 3x12-15\n• Calf Raises: 4x15-20\n• Lunges: 3x10-12 per leg\n\n**Schedule:** Mon-Push, Tue-Pull, Wed-Legs, Thu-Rest, Fri-Push, Sat-Pull, Sun-Rest`,

      `**PPL Workout Variation 2 - Hypertrophy Focus**\n\n**Push Day:**\n• Dumbbell Bench Press: 4x10-15\n• Incline Barbell Press: 3x10-12\n• Cable Crossovers: 3x15-20\n• Dumbbell Shoulder Press: 3x10-15\n• Cable Lateral Raises: 4x15-20\n• Overhead Tricep Extensions: 3x12-15\n• Dips: 3x failure\n\n**Pull Day:**\n• T-Bar Rows: 4x10-12\n• Wide Grip Pulldowns: 3x10-15\n• Single Arm Dumbbell Rows: 3x12-15 per arm\n• Reverse Flyes: 3x15-20\n• Preacher Curls: 3x10-12\n• Concentration Curls: 3x12-15\n\n**Legs Day:**\n• Front Squats: 4x8-12\n• Romanian Deadlifts: 3x10-12\n• Hack Squats: 3x10-15\n• Leg Extensions: 4x15-20\n• Lying Leg Curls: 3x12-15\n• Seated Calf Raises: 5x15-20\n\n**Schedule:** Push-Pull-Legs-Rest-Repeat`,

      `**PPL Workout Variation 3 - Strength Focus**\n\n**Push Day:**\n• Bench Press: 5x5 (heavy)\n• Close Grip Bench Press: 4x6-8\n• Military Press: 4x6-8\n• Weighted Dips: 3x8-10\n• Plate Loaded Shoulder Press: 3x8-10\n• JM Press: 3x8-10\n\n**Pull Day:**\n• Deadlifts: 3x3-5 (heavy)\n• Weighted Pull-ups: 4x6-8\n• Pendlay Rows: 4x6-8\n• Chest Supported Rows: 3x8-10\n• Barbell Curls: 4x8-10\n• Reverse Curls: 3x10-12\n\n**Legs Day:**\n• Low Bar Squats: 5x5 (heavy)\n• Power Cleans: 5x3\n• Bulgarian Split Squats: 3x8-10 per leg\n• Good Mornings: 3x8-10\n• Standing Calf Raises: 4x10-12\n\n**Schedule:** Push-Rest-Pull-Rest-Legs-Rest-Rest`,

      `**PPL Workout Variation 4 - Beginner Friendly**\n\n**Push Day:**\n• Machine Chest Press: 3x10-15\n• Machine Shoulder Press: 3x10-15\n• Push-ups: 3x failure\n• Dumbbell Lateral Raises: 3x12-15\n• Tricep Rope Pushdowns: 3x12-15\n• Bench Dips: 3x failure\n\n**Pull Day:**\n• Lat Pulldown Machine: 3x10-15\n• Seated Row Machine: 3x10-15\n• Assisted Pull-ups: 3x failure\n• Face Pulls: 3x15-20\n• Machine Bicep Curls: 3x12-15\n• Band Pull-aparts: 3x15-20\n\n**Legs Day:**\n• Goblet Squats: 3x10-15\n• Leg Press Machine: 3x12-15\n• Lying Leg Curls: 3x12-15\n• Leg Extensions: 3x12-15\n• Bodyweight Lunges: 3x10-12 per leg\n• Bodyweight Calf Raises: 4x15-20\n\n**Schedule:** Mon-Push, Tue-Pull, Wed-Legs, Thu-Rest, Repeat`,

      `**PPL Workout Variation 5 - Advanced Volume**\n\n**Push Day:**\n• Bench Press: 4x8-12\n• Incline Dumbbell Press: 4x10-12\n• Decline Bench Press: 3x10-12\n• Cable Flyes: 3x15-20\n• Arnold Press: 4x10-12\n• Lateral Raise Dropsets: 3x failure\n• Rope Pushdowns: 4x12-15\n• Overhead Cable Extensions: 3x12-15\n\n**Pull Day:**\n• Deadlifts: 3x5-8\n• Pull-ups: 4x failure\n• Barbell Rows: 4x8-12\n• Single Arm Cable Rows: 3x12-15\n• Straight Arm Pulldowns: 3x15-20\n• Incline Dumbbell Curls: 4x10-12\n• Hammer Curls: 3x12-15\n• Reverse Curls: 3x15-20\n\n**Legs Day:**\n• Squats: 4x8-12\n• Leg Press: 4x12-15\n• Walking Lunges: 3x20 steps per leg\n• Stiff Leg Deadlifts: 3x10-12\n• Leg Extensions: 4x15-20\n• Seated Leg Curls: 3x15-20\n• Calf Raises: 5x20-25\n\n**Schedule:** Push-Pull-Legs-Push-Pull-Legs-Rest`,
    ],
  },

  // ENHANCED: Upper/Lower Workout Plans with multiple variations and alternative phrasing
  upperLowerWorkouts: {
    patterns: [
      /upper lower workout/i,
      /upper.?lower workout/i,
      /provide.*upper lower/i,
      /give.*upper lower/i,
      /show.*upper lower/i,
      /create.*upper lower/i,
      /make.*upper lower/i,
      /design.*upper lower/i,
      /upper lower routine/i,
      /upper.?lower routine/i,
      /upper lower program/i,
      /upper.?lower program/i,
      /upper lower training/i,
      /upper.?lower training/i,
      /upper lower split workout/i,
      /upper.?lower split workout/i,
      /i want upper lower/i,
      /need upper lower workout/i,
      /looking for upper lower/i,
      /suggest upper lower/i,
      /recommend upper lower/i,
      /can you.*upper lower/i,
      /want.*upper lower/i,
      /get.*upper lower/i,
      /need.*upper lower/i,
      /want.*upper lower/i,
      /show.*upper lower/i,
      /give.*upper lower/i,
      /create.*upper lower/i,
      /make.*upper lower/i,
      /design.*upper lower/i,
      /upper lower plan/i,
      /upper.?lower plan/i,
      /upper lower schedule/i,
      /upper.?lower schedule/i,
      /upper lower split/i,
      /upper.?lower split/i,
      /i need an upper lower/i,
      /can i get upper lower/i,
      /hook me up with upper lower/i,
      /upper lower workout plan/i,
      /upper.?lower workout plan/i,
      /upper body lower body/i,
      /upper and lower/i,
      /upper lower body/i,
      /another upper lower/i,
      /different upper lower/i,
      /new upper lower/i,
      /next upper lower/i,
      /more upper lower/i,
    ],
    responses: [
      `**Upper/Lower Workout Variation 1 - Balanced Strength**\n\n**Upper Body Day A:**\n• Bench Press: 4x8-12\n• Bent Over Rows: 4x8-12\n• Overhead Press: 3x8-12\n• Pull-ups: 3x failure\n• Incline Dumbbell Press: 3x10-12\n• Face Pulls: 3x15-20\n\n**Lower Body Day A:**\n• Squats: 4x6-10\n• Romanian Deadlifts: 3x8-12\n• Leg Press: 3x10-15\n• Leg Curls: 3x12-15\n• Calf Raises: 4x15-20\n\n**Upper Body Day B:**\n• Incline Bench Press: 4x8-12\n• Lat Pulldowns: 4x8-12\n• Dumbbell Shoulder Press: 3x10-12\n• Chest Supported Rows: 3x10-12\n• Lateral Raises: 3x15-20\n• Tricep/Bicep Superset: 3x12-15\n\n**Lower Body Day B:**\n• Deadlifts: 3x5-8\n• Front Squats: 3x8-12\n• Bulgarian Split Squats: 3x10-12 per leg\n• Glute Bridges: 3x12-15\n• Seated Calf Raises: 4x15-20\n\n**Schedule:** Mon-Upper A, Tue-Lower A, Wed-Rest, Thu-Upper B, Fri-Lower B, Weekend-Rest`,

      `**Upper/Lower Workout Variation 2 - Hypertrophy Focus**\n\n**Upper Body Day A:**\n• Dumbbell Bench Press: 4x10-15\n• Cable Rows: 4x10-15\n• Arnold Press: 3x10-12\n• Wide Grip Pulldowns: 3x10-15\n• Incline Dumbbell Flyes: 3x15-20\n• Cable Crossovers: 3x15-20\n\n**Lower Body Day A:**\n• Back Squats: 4x8-12\n• Leg Press: 4x12-15\n• Lying Leg Curls: 3x12-15\n• Leg Extensions: 3x15-20\n• Standing Calf Raises: 4x15-20\n• Hip Thrusts: 3x12-15\n\n**Upper Body Day B:**\n• Close Grip Bench Press: 4x10-12\n• T-Bar Rows: 4x10-12\n• Lateral Raises: 4x15-20\n• Reverse Flyes: 3x15-20\n• Skull Crushers: 3x10-12\n• Preacher Curls: 3x10-12\n\n**Lower Body Day B:**\n• Sumo Deadlifts: 3x8-10\n• Hack Squats: 3x10-15\n• Romanian Deadlifts: 3x10-12\n• Seated Leg Curls: 3x12-15\n• Calf Press: 4x20-25\n• Walking Lunges: 3x20 steps\n\n**Schedule:** Upper-Lower-Rest-Upper-Lower-Rest-Rest`,

      `**Upper/Lower Workout Variation 3 - Strength Focus**\n\n**Upper Body Day A:**\n• Bench Press: 5x5\n• Pendlay Rows: 4x6-8\n• Standing Military Press: 4x6-8\n• Weighted Pull-ups: 4x6-8\n• Close Grip Bench: 3x8-10\n• Barbell Curls: 3x8-10\n\n**Lower Body Day A:**\n• Squats: 5x5\n• Conventional Deadlifts: 3x3-5\n• Bulgarian Split Squats: 3x8-10\n• Good Mornings: 3x8-10\n• Calf Raises: 4x10-12\n\n**Upper Body Day B:**\n• Incline Bench Press: 4x6-8\n• Chest Supported Rows: 4x6-8\n• Push Press: 4x5\n• Face Pulls: 3x15-20\n• Tricep Extensions: 3x8-10\n• Hammer Curls: 3x8-10\n\n**Lower Body Day B:**\n• Front Squats: 4x6-8\n• Romanian Deadlifts: 3x8-10\n• Leg Press: 3x10-12\n• Glute Ham Raises: 3x8-10\n• Seated Calf Raises: 4x12-15\n\n**Schedule:** Upper A-Rest-Lower A-Rest-Upper B-Rest-Lower B`,

      `**Upper/Lower Workout Variation 4 - Beginner Friendly**\n\n**Upper Body Day A:**\n• Machine Chest Press: 3x10-15\n• Machine Rows: 3x10-15\n• Machine Shoulder Press: 3x10-15\n• Assisted Pull-ups: 3x failure\n• Push-ups: 3x failure\n• Band Pull-aparts: 3x15-20\n\n**Lower Body Day A:**\n• Goblet Squats: 3x10-15\n• Leg Press: 3x12-15\n• Leg Curls: 3x12-15\n• Leg Extensions: 3x12-15\n• Bodyweight Calf Raises: 4x15-20\n• Bodyweight Glute Bridges: 3x15-20\n\n**Upper Body Day B:**\n• Incline Machine Press: 3x10-15\n• Lat Pulldown Machine: 3x10-15\n• Dumbbell Shoulder Press: 3x10-15\n• Machine Rows: 3x10-15\n• Dumbbell Curls: 3x12-15\n• Tricep Pushdowns: 3x12-15\n\n**Lower Body Day B:**\n• Bodyweight Squats: 3x15-20\n• Romanian Deadlifts (light): 3x10-12\n• Lunges: 3x10-12 per leg\n• Calf Raises: 4x15-20\n• Planks: 3x30-60 seconds\n\n**Schedule:** Mon-Upper A, Tue-Lower A, Wed-Rest, Thu-Upper B, Fri-Lower B, Weekend Active Recovery`,
    ],
  },

  // ENHANCED: Bro Split Workout Plans with multiple variations and alternative phrasing
  broSplitWorkouts: {
    patterns: [
      /bro split workout/i,
      /bro.?split workout/i,
      /body.?part split workout/i,
      /provide.*bro split/i,
      /give.*bro split/i,
      /show.*bro split/i,
      /create.*bro split/i,
      /make.*bro split/i,
      /design.*bro split/i,
      /bro split routine/i,
      /bro.?split routine/i,
      /bro split program/i,
      /bro.?split program/i,
      /bro split training/i,
      /bro.?split training/i,
      /body.?part split routine/i,
      /i want bro split/i,
      /need bro split workout/i,
      /looking for bro split/i,
      /suggest bro split/i,
      /recommend bro split/i,
      /can you.*bro split/i,
      /want.*bro split/i,
      /get.*bro split/i,
      /need.*bro split/i,
      /want.*bro split/i,
      /show.*bro split/i,
      /give.*bro split/i,
      /create.*bro split/i,
      /make.*bro split/i,
      /design.*bro split/i,
      /bro split plan/i,
      /bro.?split plan/i,
      /bro split schedule/i,
      /bro.?split schedule/i,
      /bro split/i,
      /bro.?split/i,
      /i need a bro split/i,
      /can i get bro split/i,
      /hook me up with bro split/i,
      /bro split workout plan/i,
      /bro.?split workout plan/i,
      /body part split/i,
      /muscle group split/i,
      /one muscle per day/i,
      /chest back shoulders arms legs/i,
      /another bro split/i,
      /different bro split/i,
      /new bro split/i,
      /next bro split/i,
      /more bro split/i,
    ],
    responses: [
      `**Bro Split Variation 1 - Classic Bodybuilding**\n\n**Monday: Chest**\n• Bench Press: 4x8-12\n• Incline Dumbbell Press: 3x10-12\n• Cable Flyes: 3x12-15\n• Push-ups: 3x failure\n• Chest Dips: 3x10-15\n\n**Tuesday: Back**\n• Deadlifts: 3x5-8\n• Pull-ups: 4x failure\n• Barbell Rows: 3x8-12\n• Lat Pulldowns: 3x10-12\n• Seated Rows: 3x10-12\n• Straight Arm Pulldowns: 3x15-20\n\n**Wednesday: Shoulders**\n• Overhead Press: 4x8-12\n• Lateral Raises: 4x12-15\n• Front Raises: 3x12-15\n• Rear Delt Flyes: 3x15-20\n• Shrugs: 4x12-15\n• Face Pulls: 3x15-20\n\n**Thursday: Arms**\n• Barbell Curls: 4x10-12\n• Tricep Pushdowns: 4x12-15\n• Hammer Curls: 3x10-12\n• Overhead Tricep Extensions: 3x12-15\n• Preacher Curls: 3x10-12\n• Skull Crushers: 3x10-12\n• Concentration Curls: 3x12-15\n\n**Friday: Legs**\n• Squats: 4x8-12\n• Leg Press: 3x10-15\n• Leg Extensions: 3x12-15\n• Leg Curls: 3x12-15\n• Calf Raises: 5x15-20\n• Lunges: 3x10-12 per leg\n\n**Weekend:** Rest or Active Recovery`,

      `**Bro Split Variation 2 - Advanced Volume**\n\n**Monday: Chest & Calves**\n• Incline Barbell Press: 4x8-12\n• Flat Dumbbell Press: 4x10-12\n• Decline Bench Press: 3x10-12\n• Cable Crossovers: 3x15-20\n• Pec Deck: 3x12-15\n• Calf Raises: 5x15-20\n\n**Tuesday: Back & Abs**\n• Deadlifts: 3x5-8\n• Wide Grip Pull-ups: 4x failure\n• T-Bar Rows: 4x8-12\n• Single Arm Dumbbell Rows: 3x10-12\n• Hyperextensions: 3x15-20\n• Cable Crunches: 4x15-20\n• Leg Raises: 3x15-20\n\n**Wednesday: Shoulders & Traps**\n• Military Press: 4x8-12\n• Dumbbell Lateral Raises: 4x12-15\n• Cable Lateral Raises: 3x15-20\n• Bent Over Lateral Raises: 3x12-15\n• Barbell Shrugs: 4x12-15\n• Upright Rows: 3x10-12\n\n**Thursday: Arms**\n• Close Grip Bench Press: 4x8-12\n• Barbell Curls: 4x8-12\n• Tricep Dips: 3x failure\n• Incline Dumbbell Curls: 3x10-12\n• Overhead Rope Extensions: 3x12-15\n• Preacher Curls: 3x10-12\n• Kickbacks: 3x12-15\n\n**Friday: Legs**\n• Squats: 4x8-12\n• Leg Press: 4x12-15\n• Romanian Deadlifts: 3x10-12\n• Leg Extensions: 4x15-20\n• Lying Leg Curls: 3x12-15\n• Seated Calf Raises: 5x15-20\n• Walking Lunges: 3x20 steps\n\n**Weekend:** Complete Rest`,

      `**Bro Split Variation 3 - Powerbuilding Style**\n\n**Monday: Chest & Triceps**\n• Bench Press: 5x5\n• Incline Dumbbell Press: 4x8-12\n• Weighted Dips: 3x8-10\n• Cable Flyes: 3x15-20\n• Close Grip Bench: 3x8-10\n• Tricep Pushdowns: 3x12-15\n\n**Tuesday: Back & Biceps**\n• Deadlifts: 3x3-5\n• Weighted Pull-ups: 4x6-8\n• Barbell Rows: 4x8-12\n• Lat Pulldowns: 3x10-12\n• Barbell Curls: 4x8-10\n• Hammer Curls: 3x10-12\n\n**Wednesday: Shoulders & Abs**\n• Overhead Press: 5x5\n• Arnold Press: 3x8-12\n• Lateral Raises: 4x12-15\n• Rear Delt Flyes: 3x15-20\n• Hanging Leg Raises: 3x15-20\n• Russian Twists: 3x20\n\n**Thursday: Legs**\n• Squats: 5x5\n• Romanian Deadlifts: 3x8-10\n• Leg Press: 4x10-15\n• Leg Curls: 3x12-15\n• Calf Raises: 5x15-20\n• Bulgarian Split Squats: 3x10-12\n\n**Friday: Arms & Calves**\n• Close Grip Bench: 4x8-12\n• Barbell Curls: 4x8-12\n• Skull Crushers: 3x10-12\n• Preacher Curls: 3x10-12\n• Tricep Dips: 3x failure\n• Concentration Curls: 3x12-15\n• Seated Calf Raises: 5x15-20\n\n**Weekend:** Active Recovery`,

      `**Bro Split Variation 4 - High Frequency Modified**\n\n**Monday: Chest & Back**\n• Bench Press: 4x8-12\n• Pull-ups: 4x failure\n• Incline Dumbbell Press: 3x10-12\n• Barbell Rows: 3x8-12\n• Cable Crossovers: 3x15-20\n• Lat Pulldowns: 3x10-12\n\n**Tuesday: Shoulders & Arms**\n• Overhead Press: 4x8-12\n• Lateral Raises: 4x12-15\n• Barbell Curls: 3x10-12\n• Tricep Pushdowns: 3x12-15\n• Rear Delt Flyes: 3x15-20\n• Hammer Curls: 3x10-12\n\n**Wednesday: Legs**\n• Squats: 4x8-12\n• Romanian Deadlifts: 3x8-12\n• Leg Press: 3x10-15\n• Leg Curls: 3x12-15\n• Calf Raises: 5x15-20\n• Lunges: 3x10-12\n\n**Thursday: Chest & Back**\n• Incline Bench Press: 4x8-12\n• T-Bar Rows: 4x8-12\n• Dumbbell Flyes: 3x12-15\n• Seated Rows: 3x10-12\n• Push-ups: 3x failure\n• Straight Arm Pulldowns: 3x15-20\n\n**Friday: Shoulders & Arms**\n• Dumbbell Shoulder Press: 4x10-12\n• Cable Lateral Raises: 4x15-20\n• Preacher Curls: 3x10-12\n• Overhead Tricep Extensions: 3x12-15\n• Face Pulls: 3x15-20\n• Concentration Curls: 3x12-15\n\n**Weekend:** Rest`,
    ],
  },

  // COMPREHENSIVE: Enhanced nutrition category with advanced sentence patterns
  nutrition: {
    patterns: [
      /diet/i,
      /nutrition/i,
      /food/i,
      /eat/i,
      /meal/i,
      /protein/i,
      /carbs/i,
      /calories/i,
      /vegetable/i,
      /fruit/i,
      /healthy eating/i,
      /meal plan/i,
      /diet plan/i,
      /what to eat/i,
      /healthy food/i,
      /nutrition plan/i,
      /macros/i,
      /macronutrients/i,
      /micronutrients/i,
      /vitamins/i,
      /minerals/i,
      /fiber/i,
      /water/i,
      /hydration/i,
      /supplements/i,
      /pre.?workout/i,
      /post.?workout/i,
      /breakfast/i,
      /lunch/i,
      /dinner/i,
      /snack/i,
      /what.*eat/i,
      /how.*eat/i,
      /when.*eat/i,
      /best.*food/i,
      /healthy.*diet/i,
      /proper.*nutrition/i,
      /diet.*advice/i,
      /nutrition.*tips/i,
      /meal.*prep/i,
      /cooking.*healthy/i,
      /grocery.*list/i,
      /shopping.*food/i,
      /weight loss.*diet/i,
      /muscle gain.*food/i,
      /protein.*sources/i,
      /carbs.*sources/i,
      /fats.*sources/i,
      /vitamin.*sources/i,
      /mineral.*sources/i,
      /should I eat.*/i,
      /what.*should.*eat/i,
      /how much.*eat/i,
      /when.*should.*eat/i,
      /best.*nutrition/i,
      /healthy.*eating/i,
      /proper.*diet/i,
      /balanced.*nutrition/i,
      /food.*choices/i,
      /eating.*habits/i,
      /nutritional.*needs/i,
      /dietary.*requirements/i,
      /food.*groups/i,
      /meal.*timing/i,
      /eating.*schedule/i,
      /portion.*control/i,
      /serving.*sizes/i,
    ],
    responses: [
      "A balanced diet should include lean proteins, complex carbs, healthy fats, and plenty of vegetables.",
      "Stay hydrated! Drink at least 8 glasses of water daily, more if you're active.",
      "Focus on whole foods and limit processed foods for better health results.",
      "Protein is essential for muscle repair - aim for 1.6-2.2g per kg of body weight.",
      "Include a variety of colorful fruits and vegetables for different vitamins and minerals.",
      "Complex carbs like whole grains, oats, and sweet potatoes provide sustained energy.",
      "Healthy fats from avocados, nuts, and olive oil support hormone production and brain health.",
      "Timing matters: Eat a balanced meal 2-3 hours before workouts and protein-rich food after.",
      "Don't skip meals - consistent eating patterns help maintain energy and metabolism.",
      "Listen to your hunger cues and eat mindfully rather than following strict rules.",
      "Include protein with every meal to support muscle maintenance and satiety.",
      "Fiber-rich foods like vegetables, fruits, and whole grains support digestive health.",
      "Plan your meals ahead to make healthier choices throughout the week.",
    ],
  },

  // COMPREHENSIVE: Enhanced weight loss category with advanced sentence patterns
  weightLoss: {
    patterns: [
      /lose weight/i,
      /weight loss/i,
      /burn fat/i,
      /slim down/i,
      /weight management/i,
      /calorie deficit/i,
      /fat loss/i,
      /get lean/i,
      /reduce weight/i,
      /weight reduction/i,
      /shed pounds/i,
      /drop weight/i,
      /body fat/i,
      /belly fat/i,
      /lose belly/i,
      /trim down/i,
      /get skinny/i,
      /weight control/i,
      /how.*lose weight/i,
      /what.*weight loss/i,
      /best way.*lose fat/i,
      /tips.*lose weight/i,
      /advice.*weight loss/i,
      /help.*lose weight/i,
      /want to lose weight/i,
      /trying to lose weight/i,
      /struggling.*lose weight/i,
      /can't lose weight/i,
      /plateau.*weight loss/i,
      /metabolism.*weight/i,
      /diet.*weight loss/i,
      /exercise.*weight loss/i,
      /cardio.*fat loss/i,
      /strength training.*weight loss/i,
      /how.*burn.*fat/i,
      /ways to.*lose weight/i,
      /strategies.*weight loss/i,
      /effective.*fat loss/i,
      /quick.*weight loss/i,
      /sustainable.*weight loss/i,
      /maintain.*weight loss/i,
      /keep.*weight off/i,
      /prevent.*weight gain/i,
      /boost.*metabolism/i,
      /increase.*fat burning/i,
      /reduce.*body fat/i,
      /lose.*inches/i,
      /get.*toned/i,
      /weight loss.*plateau/i,
      /stuck.*losing weight/i,
    ],
    responses: [
      "Weight loss requires a calorie deficit through diet and exercise. Aim for 1-2 lbs per week.",
      "Combine cardio with strength training for effective fat loss while preserving muscle.",
      "Track your food intake and stay consistent with your workout routine!",
      "Focus on sustainable habits rather than quick fixes for long-term weight management.",
      "Create a 300-500 calorie deficit daily through diet and exercise for steady weight loss.",
      "High-intensity interval training (HIIT) is very effective for fat burning.",
      "Build muscle through strength training - more muscle means higher resting metabolism.",
      "Be patient! Sustainable weight loss takes time - aim for consistency over perfection.",
      "Focus on nutrient-dense foods that keep you full longer like proteins and fiber-rich vegetables.",
      "Stay consistent with both diet and exercise - small daily efforts lead to big results over time.",
      "Don't eliminate food groups - focus on portion control and balanced nutrition instead.",
      "Incorporate both cardio and strength training for optimal fat loss and muscle preservation.",
      "Get enough sleep and manage stress, as both significantly impact weight loss efforts.",
    ],
  },

  // COMPREHENSIVE: Enhanced muscle gain category with advanced sentence patterns
  muscleGain: {
    patterns: [
      /build muscle/i,
      /muscle gain/i,
      /get bigger/i,
      /bulk up/i,
      /strength gain/i,
      /gain mass/i,
      /muscle growth/i,
      /hypertrophy/i,
      /get stronger/i,
      /increase muscle/i,
      /muscle building/i,
      /bulking/i,
      /mass gain/i,
      /size gain/i,
      /get muscular/i,
      /how.*build muscle/i,
      /what.*muscle gain/i,
      /best way.*gain muscle/i,
      /tips.*muscle growth/i,
      /advice.*build muscle/i,
      /help.*gain muscle/i,
      /want to build muscle/i,
      /trying to gain muscle/i,
      /struggling.*gain muscle/i,
      /can't gain muscle/i,
      /plateau.*muscle gain/i,
      /diet.*muscle gain/i,
      /nutrition.*muscle growth/i,
      /protein.*muscle/i,
      /workout.*muscle gain/i,
      /strength training.*muscle/i,
      /how.*get bigger/i,
      /ways to.*build muscle/i,
      /strategies.*muscle growth/i,
      /effective.*muscle building/i,
      /quick.*muscle gain/i,
      /natural.*muscle growth/i,
      /increase.*strength/i,
      /get.*stronger/i,
      /build.*size/i,
      /gain.*mass/i,
      /muscle.*development/i,
      /bodybuilding/i,
      /get.*jacked/i,
      /muscle.*hypertrophy/i,
      /muscle.*plateau/i,
      /stuck.*gaining muscle/i,
    ],
    responses: [
      "For muscle growth, focus on progressive overload in your strength training.",
      "Eat in a slight calorie surplus with adequate protein (1.6-2.2g per kg of body weight).",
      "Allow 48 hours recovery between working the same muscle groups.",
      "Compound exercises like squats, deadlifts, and bench presses are great for building mass.",
      "Aim for 8-12 reps per set for hypertrophy with 60-90 seconds rest between sets.",
      "Consistency is key - stick to your training and nutrition plan for at least 3 months.",
      "Get enough sleep! Muscle growth happens during recovery, not just in the gym.",
      "Track your progress with measurements and photos, not just scale weight.",
      "Focus on compound movements that work multiple muscle groups simultaneously.",
      "Ensure you're eating enough calories - muscle building requires energy surplus.",
      "Prioritize protein intake spread throughout the day for optimal muscle synthesis.",
      "Be patient - muscle growth is a slow process that requires consistent effort.",
      "Vary your rep ranges and exercises to continuously challenge your muscles.",
    ],
  },

  // COMPREHENSIVE: Enhanced recovery category with advanced sentence patterns
  recovery: {
    patterns: [
      /recovery/i,
      /rest/i,
      /sleep/i,
      /overtraining/i,
      /sore/i,
      /stretch/i,
      /flexibility/i,
      /yoga/i,
      /rest day/i,
      /days off/i,
      /muscle sore/i,
      /DOMS/i,
      /fatigue/i,
      /tired/i,
      /overtrained/i,
      /burnout/i,
      /rest period/i,
      /active recovery/i,
      /foam roll/i,
      /massage/i,
      /mobility/i,
      /how.*recover/i,
      /what.*recovery/i,
      /best way.*recover/i,
      /tips.*recovery/i,
      /help.*recover/i,
      /sore muscles/i,
      /muscle pain/i,
      /body ache/i,
      /improve recovery/i,
      /better sleep/i,
      /sleep quality/i,
      /rest days/i,
      /overtraining symptoms/i,
      /prevent overtraining/i,
      /how.*reduce.*soreness/i,
      /ways to.*recover/i,
      /speed up.*recovery/i,
      /muscle.*recovery/i,
      /body.*recovery/i,
      /training.*recovery/i,
      /exercise.*recovery/i,
      /reduce.*fatigue/i,
      /combat.*tiredness/i,
      /improve.*sleep/i,
      /better.*rest/i,
      /active.*rest/i,
      /deload/i,
      /training.*break/i,
      /recovery.*techniques/i,
      /muscle.*repair/i,
    ],
    responses: [
      "Aim for 7-9 hours of quality sleep nightly for optimal recovery.",
      "Active recovery like walking or light stretching can help with muscle soreness.",
      "Listen to your body - rest days are crucial for progress!",
      "Stretching and foam rolling can improve flexibility and reduce injury risk.",
      "Signs of overtraining: persistent fatigue, decreased performance, mood changes, frequent illness.",
      "Take 1-2 complete rest days per week, or do active recovery on those days.",
      "Proper nutrition and hydration significantly impact your recovery speed.",
      "Consider deload weeks every 6-8 weeks where you reduce training volume by 40-60%.",
      "Stay hydrated throughout the day to support muscle recovery and overall function.",
      "Incorporate mobility work into your routine to maintain joint health and flexibility.",
      "Listen to pain signals - sharp pain means stop, soreness means recover.",
      "Prioritize sleep quality by maintaining consistent sleep and wake times.",
      "Use contrast therapy (hot/cold) to reduce inflammation and improve recovery.",
    ],
  },

  // COMPREHENSIVE: Enhanced motivation category with advanced sentence patterns
  motivation: {
    patterns: [
      /motivation/i,
      /stuck/i,
      /plateau/i,
      /give up/i,
      /hard/i,
      /difficult/i,
      /demotivated/i,
      /lose motivation/i,
      /not motivated/i,
      /can't continue/i,
      /want to quit/i,
      /frustrated/i,
      /discouraged/i,
      /progress stopped/i,
      /not seeing results/i,
      /bored with workout/i,
      /exercise boredom/i,
      /routine stale/i,
      /how.*stay motivated/i,
      /what.*motivation/i,
      /tips.*motivation/i,
      /help.*motivated/i,
      /losing motivation/i,
      /can't stay consistent/i,
      /want to give up/i,
      /frustrated with progress/i,
      /not seeing results/i,
      /bored of workout/i,
      /routine getting boring/i,
      /how to keep going/i,
      /stay consistent/i,
      /how.*keep.*motivated/i,
      /ways to.*stay motivated/i,
      /find.*motivation/i,
      /lack.*motivation/i,
      /exercise.*boredom/i,
      /workout.*boring/i,
      /routine.*monotonous/i,
      /fitness.*rut/i,
      /training.*plateau/i,
      /progress.*stalled/i,
      /not.*improving/i,
      /stuck.*same weight/i,
      /can't.*progress/i,
      /frustrated.*results/i,
      /discouraged.*progress/i,
    ],
    responses: [
      "Progress takes time! Celebrate small victories and stay consistent.",
      "Mix up your routine to overcome plateaus - try new exercises or intensity techniques.",
      "Remember why you started! Every workout brings you closer to your goals. 💪",
      "Find a workout buddy or track your progress to stay motivated long-term.",
      "Plateaus are normal! Change one variable: intensity, volume, exercise selection, or rest periods.",
      "Focus on the process, not just the outcome. Enjoy the journey of getting stronger and healthier.",
      "Set small, achievable goals and reward yourself when you reach them.",
      "Remember how far you've come! Look back at old photos or fitness logs to see your progress.",
      "Try new activities or classes to keep your fitness journey exciting and fresh.",
      "Focus on how exercise makes you feel rather than just how it makes you look.",
      "Create a consistent routine that becomes a habit rather than relying on motivation alone.",
      "Surround yourself with positive influences who support your fitness goals.",
      "Remember that even short workouts are better than no workouts - consistency trumps perfection.",
    ],
  },

  // ULTRA-COMPREHENSIVE: General health category with advanced sentence patterns
  generalHealth: {
    patterns: [
      /health/i,
      /wellness/i,
      /healthy/i,
      /lifestyle/i,
      /fitness/i,
      /well.?being/i,
      /healthy lifestyle/i,
      /wellness tips/i,
      /health advice/i,
      /stay healthy/i,
      /health benefits/i,
      /fitness benefits/i,
      /why exercise/i,
      /importance of fitness/i,
      /healthier life/i,
      /improve health/i,
      /better health/i,
      /health goals/i,
      /fitness goals/i,
      /lifestyle changes/i,
      /healthy habits/i,
      /wellness routine/i,
      /how.*be.*healthy/i,
      /ways to.*improve health/i,
      /better.*lifestyle/i,
      /healthy.*living/i,
      /improve.*wellness/i,
      /boost.*health/i,
      /enhance.*fitness/i,
      /overall.*health/i,
      /general.*fitness/i,
      /physical.*health/i,
      /mental.*health/i,
      /body.*health/i,
      /mind.*body/i,
      /holistic.*health/i,
      /prevent.*disease/i,
      /disease.*prevention/i,
      /long.*term.*health/i,
      /healthy.*aging/i,
      /quality.*life/i,
      /life.*expectancy/i,
      /health.*span/i,
    ],
    responses: [
      "Regular exercise and balanced nutrition are key to overall health.",
      "Don't forget mental health - stress management and adequate sleep are crucial!",
      "Consistency in healthy habits leads to long-term wellness success.",
      "A holistic approach including exercise, nutrition, and mental wellness is best.",
      "Small, consistent healthy choices create big results over time.",
      "Balance is key - allow yourself flexibility while maintaining overall healthy habits.",
      "Physical health supports mental health and vice versa - they're interconnected.",
      "Make health a lifestyle, not a temporary fix for lasting results.",
      "Focus on sustainable changes you can maintain long-term rather than quick fixes.",
      "Incorporate movement throughout your day, not just during dedicated workout times.",
      "Prioritize sleep, nutrition, exercise, and stress management for comprehensive health.",
      "Listen to your body's signals and adjust your approach accordingly.",
      "Remember that health is a journey, not a destination - enjoy the process!",
    ],
  },

  // COMPREHENSIVE: Specific body part training
  bodyPartTraining: {
    patterns: [
      /how.*train.*(chest|pectoral)/i,
      /best.*(chest|pectoral).*exercise/i,
      /build.*(chest|pectoral)/i,
      /how.*train.*(back|lats)/i,
      /best.*(back|lats).*exercise/i,
      /build.*(back|lats)/i,
      /how.*train.*(legs|quads|hamstrings|glutes)/i,
      /best.*(legs|quads|hamstrings|glutes).*exercise/i,
      /build.*(legs|quads|hamstrings|glutes)/i,
      /how.*train.*(shoulders|delts)/i,
      /best.*(shoulders|delts).*exercise/i,
      /build.*(shoulders|delts)/i,
      /how.*train.*(arms|biceps|triceps)/i,
      /best.*(arms|biceps|triceps).*exercise/i,
      /build.*(arms|biceps|triceps)/i,
      /how.*train.*(abs|core)/i,
      /best.*(abs|core).*exercise/i,
      /build.*(abs|core)/i,
      /(chest|back|legs|shoulders|arms|abs).*workout/i,
      /(chest|back|legs|shoulders|arms|abs).*routine/i,
      /(chest|back|legs|shoulders|arms|abs).*training/i,
      /exercises for.*(chest|back|legs|shoulders|arms|abs)/i,
      /workout for.*(chest|back|legs|shoulders|arms|abs)/i,
      /routine for.*(chest|back|legs|shoulders|arms|abs)/i,
    ],
    responses: [
      "**Chest Training:** Focus on bench press variations, dumbbell presses, and flyes. Include both flat and incline movements for complete development.",
      "**Back Training:** Incorporate pull-ups, rows, and pulldowns. Work both width (lats) and thickness (middle back) for a complete back.",
      "**Leg Training:** Squats, deadlifts, and lunges are foundational. Include quad, hamstring, and glute exercises for balanced leg development.",
      "**Shoulder Training:** Military press, lateral raises, and rear delt flyes hit all three deltoid heads for rounded shoulders.",
      "**Arm Training:** Bicep curls and tricep extensions are essential. Include both compound and isolation movements for full arm development.",
      "**Core Training:** Planks, leg raises, and rotational movements build a strong core. Don't just focus on aesthetics - core strength supports all movements.",
      "**For any muscle group:** Use a mix of compound and isolation exercises, focus on progressive overload, and allow adequate recovery between sessions.",
    ],
  },

  // COMPREHENSIVE: Exercise technique and form
  exerciseTechnique: {
    patterns: [
      /how.*do.*(squat|deadlift|bench press|shoulder press|row)/i,
      /proper.*form.*(squat|deadlift|bench press|shoulder press|row)/i,
      /correct.*technique.*(squat|deadlift|bench press|shoulder press|row)/i,
      /how.*perform.*(squat|deadlift|bench press|shoulder press|row)/i,
      /(squat|deadlift|bench press|shoulder press|row).*form/i,
      /(squat|deadlift|bench press|shoulder press|row).*technique/i,
      /(squat|deadlift|bench press|shoulder press|row).*how to/i,
      /exercise.*form/i,
      /proper.*exercise/i,
      /correct.*form/i,
      /good.*technique/i,
      /safe.*exercise/i,
      /prevent.*injury/i,
      /avoid.*injury/i,
      /injury.*prevention/i,
      /exercise.*safety/i,
      /training.*safety/i,
    ],
    responses: [
      "**Proper Form Principles:** Always maintain a neutral spine, engage your core, and move through a full range of motion controlled by your muscles, not momentum.",
      "**Squat Form:** Keep chest up, back straight, knees tracking over toes. Descend until thighs are parallel to floor or as deep as mobility allows.",
      "**Deadlift Form:** Keep bar close to body, back flat, hips and shoulders rising together. Drive through heels and squeeze glutes at the top.",
      "**Bench Press Form:** Retract shoulder blades, maintain arch in upper back, lower bar to mid-chest, drive feet into floor for stability.",
      "**General Technique:** Start with lighter weights to master form before increasing load. Film yourself to check technique or ask a qualified trainer for feedback.",
      "**Injury Prevention:** Warm up properly, use appropriate weights, maintain good form, and listen to your body's pain signals (sharp pain = stop).",
      "**Progressive Overload:** Gradually increase weight, reps, or sets while maintaining proper form to continue making progress safely.",
    ],
  },

  // COMPREHENSIVE: Fitness for specific populations
  specificPopulations: {
    patterns: [
      /exercise.*(beginner|new|start)/i,
      /(beginner|new).*workout/i,
      /start.*exercising/i,
      /begin.*fitness/i,
      /exercise.*(older|senior|elderly)/i,
      /(older|senior|elderly).*workout/i,
      /exercise.*(pregnant|pregnancy)/i,
      /(pregnant|pregnancy).*workout/i,
      /exercise.*(injured|injury)/i,
      /(injured|injury).*workout/i,
      /exercise.*(medical condition|health issue)/i,
      /workout.*(medical condition|health issue)/i,
      /fitness.*(beginner|older|pregnant|injured)/i,
      /training.*(beginner|older|pregnant|injured)/i,
    ],
    responses: [
      "**For Beginners:** Start slowly with 2-3 days per week. Focus on learning proper form with bodyweight or light weights before progressing.",
      "**For Older Adults:** Include strength training to maintain muscle mass, balance exercises for fall prevention, and flexibility work. Consult your doctor first.",
      "**During Pregnancy:** Focus on moderate intensity, avoid exercises lying on back after first trimester, and listen to your body. Consult your healthcare provider.",
      "**With Injuries:** Work around injuries rather than through pain. Focus on exercises that don't aggravate the injury and consult a physical therapist.",
      "**General Advice:** Always consult with healthcare providers before starting new exercise programs if you have health conditions or concerns.",
      "**Adaptation Principle:** Any exercise can be modified to suit your current ability level. The key is consistent, safe movement.",
      "**Progress Slowly:** Regardless of your situation, progress gradually and listen to your body's feedback to avoid setbacks.",
    ],
  },
};

// Food database with categories to avoid redundancy
const foodDatabase = {
  proteins: [
    {
      name: "Chicken Breast",
      calories: 165,
      protein: 31,
      carbs: 0,
      fat: 3.6,
      type: "lean",
    },
    {
      name: "Salmon",
      calories: 206,
      protein: 22,
      carbs: 0,
      fat: 13,
      type: "fatty",
    },
    {
      name: "Lean Beef",
      calories: 250,
      protein: 26,
      carbs: 0,
      fat: 15,
      type: "lean",
    },
    {
      name: "Eggs",
      calories: 155,
      protein: 13,
      carbs: 1.1,
      fat: 11,
      type: "balanced",
    },
    {
      name: "Greek Yogurt",
      calories: 59,
      protein: 10,
      carbs: 3.6,
      fat: 0.4,
      type: "lean",
    },
    {
      name: "Tofu",
      calories: 76,
      protein: 8,
      carbs: 1.9,
      fat: 4.8,
      type: "plant",
    },
    {
      name: "Turkey Breast",
      calories: 135,
      protein: 30,
      carbs: 0,
      fat: 1,
      type: "lean",
    },
    {
      name: "Tuna",
      calories: 132,
      protein: 30,
      carbs: 0,
      fat: 1,
      type: "lean",
    },
    {
      name: "Cottage Cheese",
      calories: 98,
      protein: 11,
      carbs: 3.4,
      fat: 4.3,
      type: "lean",
    },
    {
      name: "Whey Protein",
      calories: 120,
      protein: 24,
      carbs: 3,
      fat: 1,
      type: "supplement",
    },
    {
      name: "Lentils",
      calories: 116,
      protein: 9,
      carbs: 20,
      fat: 0.4,
      type: "plant",
    },
    {
      name: "Chickpeas",
      calories: 164,
      protein: 9,
      carbs: 27,
      fat: 2.6,
      type: "plant",
    },
    {
      name: "Pork Tenderloin",
      calories: 143,
      protein: 26,
      carbs: 0,
      fat: 3.5,
      type: "lean",
    },
    {
      name: "Shrimp",
      calories: 99,
      protein: 24,
      carbs: 0.2,
      fat: 0.3,
      type: "lean",
    },
  ],

  carbs: [
    {
      name: "Brown Rice",
      calories: 112,
      protein: 2.6,
      carbs: 23,
      fat: 0.9,
      type: "complex",
    },
    {
      name: "Sweet Potato",
      calories: 86,
      protein: 1.6,
      carbs: 20,
      fat: 0.1,
      type: "complex",
    },
    {
      name: "Oats",
      calories: 66,
      protein: 2.4,
      carbs: 12,
      fat: 1.4,
      type: "complex",
    },
    {
      name: "Quinoa",
      calories: 120,
      protein: 4.4,
      carbs: 21,
      fat: 1.9,
      type: "complex",
    },
    {
      name: "Whole Wheat Bread",
      calories: 79,
      protein: 3.1,
      carbs: 13,
      fat: 1,
      type: "complex",
    },
    {
      name: "Pasta (Whole Wheat)",
      calories: 124,
      protein: 5,
      carbs: 25,
      fat: 0.6,
      type: "complex",
    },
    {
      name: "Banana",
      calories: 105,
      protein: 1.3,
      carbs: 27,
      fat: 0.4,
      type: "fruit",
    },
    {
      name: "Apple",
      calories: 95,
      protein: 0.5,
      carbs: 25,
      fat: 0.3,
      type: "fruit",
    },
    {
      name: "Berries",
      calories: 57,
      protein: 0.7,
      carbs: 14,
      fat: 0.3,
      type: "fruit",
    },
    {
      name: "Potato",
      calories: 77,
      protein: 2,
      carbs: 17,
      fat: 0.1,
      type: "complex",
    },
  ],

  fats: [
    {
      name: "Avocado",
      calories: 160,
      protein: 2,
      carbs: 9,
      fat: 15,
      type: "healthy",
    },
    {
      name: "Almonds",
      calories: 164,
      protein: 6,
      carbs: 6,
      fat: 14,
      type: "nuts",
    },
    {
      name: "Olive Oil",
      calories: 119,
      protein: 0,
      carbs: 0,
      fat: 14,
      type: "oil",
    },
    {
      name: "Peanut Butter",
      calories: 94,
      protein: 4,
      carbs: 3,
      fat: 8,
      type: "nuts",
    },
    {
      name: "Chia Seeds",
      calories: 58,
      protein: 2,
      carbs: 5,
      fat: 4,
      type: "seeds",
    },
    {
      name: "Walnuts",
      calories: 185,
      protein: 4,
      carbs: 4,
      fat: 18,
      type: "nuts",
    },
    {
      name: "Flax Seeds",
      calories: 55,
      protein: 1.9,
      carbs: 3,
      fat: 4.3,
      type: "seeds",
    },
    {
      name: "Coconut Oil",
      calories: 121,
      protein: 0,
      carbs: 0,
      fat: 14,
      type: "oil",
    },
  ],

  vegetables: [
    {
      name: "Broccoli",
      calories: 31,
      protein: 2.6,
      carbs: 6,
      fat: 0.3,
      type: "cruciferous",
    },
    {
      name: "Spinach",
      calories: 7,
      protein: 0.9,
      carbs: 1.1,
      fat: 0.1,
      type: "leafy",
    },
    {
      name: "Kale",
      calories: 33,
      protein: 2.9,
      carbs: 6,
      fat: 0.6,
      type: "leafy",
    },
    {
      name: "Carrots",
      calories: 41,
      protein: 0.9,
      carbs: 10,
      fat: 0.2,
      type: "root",
    },
    {
      name: "Bell Peppers",
      calories: 31,
      protein: 1,
      carbs: 6,
      fat: 0.3,
      type: "colorful",
    },
    {
      name: "Cauliflower",
      calories: 25,
      protein: 2,
      carbs: 5,
      fat: 0.3,
      type: "cruciferous",
    },
    {
      name: "Asparagus",
      calories: 20,
      protein: 2.2,
      carbs: 3.9,
      fat: 0.1,
      type: "green",
    },
    {
      name: "Brussels Sprouts",
      calories: 38,
      protein: 3,
      carbs: 8,
      fat: 0.3,
      type: "cruciferous",
    },
  ],
};

// Track last used responses for each category to avoid repetition
const lastUsedResponses = {};

// Advanced sentence understanding and response generation
export const getFitnessResponse = (userInput) => {
  const input = userInput.toLowerCase().trim();

  // Check for greetings first
  if (
    fitnessHealthData.greetings.patterns.some((pattern) => pattern.test(input))
  ) {
    const randomIndex = Math.floor(
      Math.random() * fitnessHealthData.greetings.responses.length
    );
    return fitnessHealthData.greetings.responses[randomIndex];
  }

  // Check for food/nutrition questions with specific food mentions
  const foodMentions = [
    {
      pattern:
        /(chicken|salmon|beef|egg|yogurt|tofu|turkey|tuna|cheese|protein)/i,
      category: "proteins",
    },
    {
      pattern: /(rice|potato|oats|quinoa|bread|pasta|banana|apple|berry)/i,
      category: "carbs",
    },
    {
      pattern:
        /(avocado|almond|olive oil|peanut butter|chia|walnut|flax|coconut)/i,
      category: "fats",
    },
    {
      pattern:
        /(broccoli|spinach|kale|carrot|pepper|cauliflower|asparagus|brussels)/i,
      category: "vegetables",
    },
  ];

  for (const food of foodMentions) {
    if (food.pattern.test(input)) {
      const foodCategory = foodDatabase[food.category];
      const randomFood =
        foodCategory[Math.floor(Math.random() * foodCategory.length)];
      return `**${randomFood.name} Nutrition** (per 100g):\n• Calories: ${
        randomFood.calories
      }\n• Protein: ${randomFood.protein}g\n• Carbs: ${
        randomFood.carbs
      }g\n• Fat: ${randomFood.fat}g\n\nGreat choice! ${
        randomFood.name
      } is excellent for ${
        food.category === "proteins"
          ? "muscle repair and growth"
          : food.category === "carbs"
          ? "energy and recovery"
          : food.category === "fats"
          ? "hormone health and energy"
          : "vitamins and fiber"
      }!`;
    }
  }

  // Advanced pattern matching for all categories with rotation
  const categories = Object.keys(fitnessHealthData).filter(
    (key) => key !== "greetings"
  );

  for (const category of categories) {
    if (
      fitnessHealthData[category].patterns.some((pattern) =>
        pattern.test(input)
      )
    ) {
      const responses = fitnessHealthData[category].responses;

      // Initialize last used index for this category if not exists
      if (!lastUsedResponses[category]) {
        lastUsedResponses[category] = -1;
      }

      // Get next response (rotate through responses)
      let nextIndex = (lastUsedResponses[category] + 1) % responses.length;
      lastUsedResponses[category] = nextIndex;

      return responses[nextIndex];
    }
  }

  // Fallback responses for any fitness/health related question
  const fallbackResponses = [
    "That's a great fitness question! For optimal results, focus on consistency in both your workouts and nutrition. Remember that small, daily improvements lead to big changes over time! 💪",

    "Excellent question about health and fitness! The key principles are progressive overload in your training, adequate protein intake, proper recovery, and consistency. Stay committed to your goals! 🏋️‍♂️",

    "I love that you're thinking about your fitness! Remember that balance is crucial - proper training, good nutrition, quality sleep, and stress management all work together for optimal results. 🌟",

    "Great health question! Whether you're focusing on strength, endurance, or overall wellness, remember that consistency beats intensity long-term. Find activities you enjoy and make them a sustainable habit! 🏃‍♀️",

    "That's an important aspect of fitness! Always prioritize proper form over heavy weights, listen to your body's signals, and remember that rest and recovery are when progress actually happens. 🛌",

    "Awesome fitness inquiry! Don't forget that nutrition is just as important as training. Fuel your body properly, stay hydrated, and be patient - real results take time and consistency! 🥗",

    "Fantastic health question! Remember that fitness is a journey, not a destination. Celebrate small victories, learn from setbacks, and keep moving forward one day at a time. You've got this! ✨",
  ];

  const randomFallback = Math.floor(Math.random() * fallbackResponses.length);
  return fallbackResponses[randomFallback];
};

// Example usage
console.log(
  "Fitness & Health Expert: Hello! Ask me anything about fitness, workouts, nutrition, weight loss, muscle gain, or health! 💪"
);

// Test the enhanced system
const testQuestions = [
  "How do I build muscle?",
  "What's the best diet for weight loss?",
  "Should I do PPL or Upper Lower?",
  "How many times a week should I workout?",
  "What are good protein sources?",
  "How do I get motivated to exercise?",
  "What's the proper form for squats?",
  "How much protein do I need?",
  "Is chicken breast good for building muscle?",
  "What's better for beginners?",
  "How do I train my chest?",
  "What should I eat before workout?",
  "How to lose belly fat?",
  "Best exercises for back?",
  "How to improve recovery?",
  "Can you give me a PPL workout?",
  "I need an upper lower routine",
  "Show me a bro split workout",
  "Provide another PPL workout",
  "Give me a different upper lower routine",
];

export function getBotResponse(message) {
  return getFitnessResponse(message);
}

// Uncomment to test various questions
// testQuestions.forEach(question => {
//   console.log(`User: ${question}`);
//   console.log(`Expert: ${getFitnessResponse(question)}\n`);
// });
